-- This SQL code was generated by sklearn2sql (development version).
-- Copyright 2018

-- Model : KerasRegressor_Dense
-- Dataset : freidman3
-- Database : firebird


-- This SQL code can contain one or more statements, to be executed in the order they appear in this file.



-- Model deployment code

WITH keras_input AS 
(SELECT "ADS"."KEY" AS "KEY", "ADS"."Feature_0" AS "Feature_0", "ADS"."Feature_1" AS "Feature_1", "ADS"."Feature_2" AS "Feature_2", "ADS"."Feature_3" AS "Feature_3" 
FROM freidman3 AS "ADS"), 
keras_input_1 AS 
(SELECT keras_input."KEY" AS "KEY", keras_input."Feature_0" AS "Feature_0", keras_input."Feature_1" AS "Feature_1", keras_input."Feature_2" AS "Feature_2", keras_input."Feature_3" AS "Feature_3" 
FROM keras_input), 
layer_dense_1 AS 
(SELECT keras_input_1."KEY" AS "KEY", 0.36409226059913635 + 0.6468045115470886 * keras_input_1."Feature_0" + 0.7715808749198914 * keras_input_1."Feature_1" + -0.137642964720726 * keras_input_1."Feature_2" + -0.38355404138565063 * keras_input_1."Feature_3" AS output_1, 0.23909898102283478 + 1.0671941041946411 * keras_input_1."Feature_0" + -0.46417513489723206 * keras_input_1."Feature_1" + 0.43661555647850037 * keras_input_1."Feature_2" + -0.5652326941490173 * keras_input_1."Feature_3" AS output_2, 0.2471257746219635 + 0.2532466948032379 * keras_input_1."Feature_0" + -0.395689457654953 * keras_input_1."Feature_1" + 0.0043100654147565365 * keras_input_1."Feature_2" + -0.21807372570037842 * keras_input_1."Feature_3" AS output_3, 0.33946141600608826 + -0.4577955901622772 * keras_input_1."Feature_0" + 0.5924004316329956 * keras_input_1."Feature_1" + 0.6363167762756348 * keras_input_1."Feature_2" + 0.8207882046699524 * keras_input_1."Feature_3" AS output_4 
FROM keras_input_1), 
layer_dense_1_1 AS 
(SELECT layer_dense_1."KEY" AS "KEY", layer_dense_1.output_1 AS output_1, layer_dense_1.output_2 AS output_2, layer_dense_1.output_3 AS output_3, layer_dense_1.output_4 AS output_4 
FROM layer_dense_1), 
layer_dense_2 AS 
(SELECT layer_dense_1_1."KEY" AS "KEY", 0.26164019107818604 + 0.3763045370578766 * layer_dense_1_1.output_1 + 0.5162962079048157 * layer_dense_1_1.output_2 + 0.8848172426223755 * layer_dense_1_1.output_3 + 0.457134872674942 * layer_dense_1_1.output_4 AS output_1 
FROM layer_dense_1_1)
 SELECT layer_dense_2."KEY" AS "KEY", layer_dense_2.output_1 AS "Estimator" 
FROM layer_dense_2