-- This SQL code was generated by sklearn2sql (development version).
-- Copyright 2018

-- Model : KerasRegressor_Dense
-- Dataset : freidman2
-- Database : oracle


-- This SQL code can contain one or more statements, to be executed in the order they appear in this file.



-- Model deployment code

WITH keras_input AS 
(SELECT "ADS"."KEY" AS "KEY", "ADS"."Feature_0" AS "Feature_0", "ADS"."Feature_1" AS "Feature_1", "ADS"."Feature_2" AS "Feature_2", "ADS"."Feature_3" AS "Feature_3" 
FROM "FREIDMAN2" "ADS"), 
keras_input_1 AS 
(SELECT keras_input."KEY" AS "KEY", keras_input."Feature_0" AS "Feature_0", keras_input."Feature_1" AS "Feature_1", keras_input."Feature_2" AS "Feature_2", keras_input."Feature_3" AS "Feature_3" 
FROM keras_input), 
layer_dense_1 AS 
(SELECT keras_input_1."KEY" AS "KEY", -0.12752391397953033 + 0.4536078870296478 * keras_input_1."Feature_0" + -0.7170146107673645 * keras_input_1."Feature_1" + -1.2954500913619995 * keras_input_1."Feature_2" + -0.8475359678268433 * keras_input_1."Feature_3" AS output_1, -0.09334033727645874 + -0.6155808568000793 * keras_input_1."Feature_0" + -0.29906973242759705 * keras_input_1."Feature_1" + -1.3182556629180908 * keras_input_1."Feature_2" + 0.6055045127868652 * keras_input_1."Feature_3" AS output_2, 0.12729860842227936 + -0.30023306608200073 * keras_input_1."Feature_0" + 0.46775707602500916 * keras_input_1."Feature_1" + 0.09395249933004379 * keras_input_1."Feature_2" + -0.5479800701141357 * keras_input_1."Feature_3" AS output_3, -0.1252007782459259 + -0.13082896173000336 * keras_input_1."Feature_0" + 0.7229157090187073 * keras_input_1."Feature_1" + -0.22813092172145844 * keras_input_1."Feature_2" + 0.4703584611415863 * keras_input_1."Feature_3" AS output_4 
FROM keras_input_1), 
layer_dense_1_1 AS 
(SELECT layer_dense_1."KEY" AS "KEY", layer_dense_1.output_1 AS output_1, layer_dense_1.output_2 AS output_2, layer_dense_1.output_3 AS output_3, layer_dense_1.output_4 AS output_4 
FROM layer_dense_1), 
layer_dense_2 AS 
(SELECT layer_dense_1_1."KEY" AS "KEY", 0.12637509405612946 + -0.8966023921966553 * layer_dense_1_1.output_1 + -0.052544791251420975 * layer_dense_1_1.output_2 + 1.0748215913772583 * layer_dense_1_1.output_3 + -0.8633612990379333 * layer_dense_1_1.output_4 AS output_1 
FROM layer_dense_1_1)
 SELECT layer_dense_2."KEY" AS "KEY", layer_dense_2.output_1 AS "Estimator" 
FROM layer_dense_2